// import Head from 'next/head'
// import Image from 'next/image'
// import axios from 'axios'

import Card from '../components/card/Card'
import styles from '../styles/Home.module.css'

export default function Home({posts}) {

  return (
    <div className={styles.container}>
      <h1 className={styles.home}>Porpular Article </h1>
      <div className={styles.card}>
        {
          posts.map(post =>
            <Card key={post.id}
              post = {post}
            />  
            )
        }
       
      </div> 
    </div>
  )
}

export const getStaticProps = async () => {
  const  res = await fetch(`https://jsonplaceholder.typicode.com/posts/`);
  const posts = await res.json();
  return {
    props: {
      posts:posts
    }
  }
}




//AXIOS way 

// export const getStaticProps = async () => {
//   const  res = await axios.get('https://jsonplaceholder.typicode.com/posts');
//   const data = await res.data;
//   return {
//     props: {
//       posts:data
//     }
//   }
// }


  //  <Head>
  //       <title>Mega Power Myanmar </title>
  //       <meta name="description" content="Generated by create next app" />
  //       <link rel="icon" href="/favicon.ico" />
  //     </Head>

  //     <main className={styles.main}>
  //       <h1 className={styles.title}>
  //         Welcome to <a href="https://nextjs.org">Mega Power Myanamar!</a>
  //       </h1>

  //       <p className={styles.description}>
  //         Get started by editing{' '}
  //         <code className={styles.code}>pages/index.js</code>
  //       </p>

  //       <div className={styles.grid}>
  //         <a href="https://nextjs.org/docs" className={styles.card}>
  //           <h2>Documentation &rarr;</h2>
  //           <p>Find in-depth information about Next.js features and API.</p>
  //         </a>

  //         <a href="https://nextjs.org/learn" className={styles.card}>
  //           <h2>Learn &rarr;</h2>
  //           <p>Learn about Next.js in an interactive course with quizzes!</p>
  //         </a>

  //         <a
  //           href="https://github.com/vercel/next.js/tree/canary/examples"
  //           className={styles.card}
  //         >
  //           <h2>Examples &rarr;</h2>
  //           <p>Discover and deploy boilerplate example Next.js projects.</p>
  //         </a>

  //         <a
  //           href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
  //           className={styles.card}
  //         >
  //           <h2>Deploy &rarr;</h2>
  //           <p>
  //             Instantly deploy your Next.js site to a public URL with Vercel.
  //           </p>
  //         </a>
  //       </div>
  //     </main>

  //     <footer className={styles.footer}>
  //       <a
  //         href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
  //         target="_blank"
  //         rel="noopener noreferrer"
  //       >
  //         Powered by{' '}
  //         <span className={styles.logo}>
  //           <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
  //         </span>
  //       </a>
  //     </footer>